DOAN_CLOUND/Controllers/Order_DetailController.cs
using DOAN_CLOUND.Models;
using System;
using System.Collections.Generic;
using System.Data.Odbc;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DOAN_CLOUND.Controllers
{
    public class Order_DetailController : Controller
    {
        // GET: Order
        public ActionResult Index()
        {
            return View();
        }

        WebCafeDataContext db = new WebCafeDataContext();

        //// Thêm Order Detail
        //[HttpGet]
        //public ActionResult Create_Order_Detail()
        //{
        //    return View();
        //}

        //[HttpPost]
        //public ActionResult Create_Order_Detail(ORDER_DETAIL order_detail)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            var existingOrderDetail = db.ORDER_DETAILs.FirstOrDefault(od => od.MAHOADON == order_detail.MAHOADON && od.MASP == order_detail.MASP);
        //            if (existingOrderDetail != null)
        //            {
        //                ModelState.AddModelError("", "Chi tiết hóa đơn đã tồn tại. Vui lòng chọn hóa đơn khác.");
        //                return View(order_detail);
        //            }
        //            db.ORDER_DETAILs.InsertOnSubmit(order_detail); // Thêm đối tượng vào bảng ORDER DETAIL
        //            db.SubmitChanges(); // Lưu thay đổi vào cơ sở dữ liệu

        //            return RedirectToAction("Index_Order", "Home");
        //        }
        //        catch (Exception ex)
        //        {
        //            ModelState.AddModelError("", "Có lỗi xảy ra khi lưu chi tiết hóa đơn: " + ex.Message);
        //        }
        //    }
        //    return View(order_detail);
        //}

        // Xóa Order Detail
        [HttpGet]
        public ActionResult Delete_Order_Detail(int mahoadon, int masp)
        {
            ORDER_DETAIL order_detail = db.ORDER_DETAILs.Single(c => c.MAHOADON == mahoadon && c.MASP == masp);
            if (order_detail == null)
            {
                return HttpNotFound();
            }
            return View(order_detail);
        }

        [HttpPost, ActionName("Delete_Order_Detail")]
        public ActionResult Delete_Order_DetailConfirmed(int mahoadon, int masp)
        {
            ORDER_DETAIL order_detail = db.ORDER_DETAILs.Single(c => c.MAHOADON == mahoadon && c.MASP == masp);
            if (order_detail == null)
            {
                return HttpNotFound();
            }
            db.ORDER_DETAILs.DeleteOnSubmit(order_detail);
            db.SubmitChanges();
            return RedirectToAction("Index_Order_Details", "Home");
        }

        // Sửa Order Detail
        [HttpGet]
        public ActionResult Update_Order_Detail(int mahoadon, int masp)
        {
            ORDER_DETAIL order_detail = db.ORDER_DETAILs.Single(c => c.MAHOADON == mahoadon && c.MASP == masp);
            if (order_detail == null)
            {
                return HttpNotFound();
            }
            return View(order_detail);
        }

        [HttpPost]
        public ActionResult Update_Order_Detail(ORDER_DETAIL updatedOrder_Details)
        {
            ORDER_DETAIL order_detail = db.ORDER_DETAILs.Single(c => c.MAHOADON == updatedOrder_Details.MAHOADON && c.MASP == updatedOrder_Details.MASP);
            if (order_detail == null)
            {
                return HttpNotFound();
            }

            order_detail.SOLUONG = updatedOrder_Details.SOLUONG;
            //order_detail.GIA = updatedOrder_Details.GIA;
            db.SubmitChanges(); // Lưu lại thay đổi (này là với linQ nha)
            return RedirectToAction("Index_Order_Details", "Home");
        }
    }
}

DOAN_CLOUND/Views/Order_Detail/Create_Order_Detail.cshtml
@model DOAN_CLOUND.Models.ORDER_DETAIL

@{
    ViewBag.Title = "Create_Order_Detail";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CreateDept</title>
    <!--Bootstrap 4-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" />
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://cdn.rawgit.com/PascaleBeier/bootstrap-validate/v2.2.0/dist/bootstrap-validate.js"></script>
</head>
<body>
    @using (Html.BeginForm("Create_Order_Detail", "Order_Detail", FormMethod.Post))
    {
        @Html.ValidationSummary(true)
        <h3 class="mt-3" style="color: blue; font-weight: bold">ADD NEW ORDER DETAIL</h3>

        <div class="editor-label">
            <h3>Add order detail infomation</h3>
        </div>

        <div class="editor-label">
            <p>Enter ID Product</p>
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MASP)
            @Html.ValidationMessageFor(model => model.MASP)
        </div>

        <div class="editor-label">
            <p>Enter Amount</p>
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.SOLUONG)
            @Html.ValidationMessageFor(model => model.SOLUONG)
        </div>

        <div class="editor-label">
            <p>Enter Price</p>
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.GIA)
            @Html.ValidationMessageFor(model => model.GIA)
        </div>

        <p class="form-group" style="margin-top: 20px">
            <input type="submit" class="btn btn-primary" value="Create" />
        </p>

        <div>
            @Html.ActionLink("Back to List", "Index_Order_Details", "Home")
        </div>
    }
</body>
</html>

DOAN_CLOUND/Views/Order_Detail/Delete_Order_Detail.cshtml
@model DOAN_CLOUND.Models.ORDER_DETAIL

@{
    ViewBag.Title = "Delete_Order_Detail";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CreateDept</title>
    <!--Bootstrap 4-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" />
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://cdn.rawgit.com/PascaleBeier/bootstrap-validate/v2.2.0/dist/bootstrap-validate.js"></script>
</head>
<body>
    <h2>Are you sure you want to delete this?</h2>

    @using (Html.BeginForm("Delete_Order_Detail", "Order_Detail", FormMethod.Post))
    {
        @Html.ValidationSummary(true)
        <h3 class="mt-3" style="color: blue; font-weight: bold">DELETE ORDER</h3>

        <div class="editor-label">
            <p>Delete Order right!</p>
        </div>
        <div class="editor-field">
            @Html.DisplayFor(model => model.MAHOADON)
            @Html.ValidationMessageFor(model => model.MAHOADON)
        </div>
        <div class="editor-field">
            @Html.DisplayFor(model => model.MASP)
            @Html.ValidationMessageFor(model => model.MASP)
        </div>
        <div class="editor-field">
            @Html.DisplayFor(model => model.SOLUONG)
            @Html.ValidationMessageFor(model => model.SOLUONG)
        </div>
        <div class="editor-field">
            @Html.DisplayFor(model => model.GIA)
            @Html.ValidationMessageFor(model => model.GIA)
        </div>

        <p class="form-group" style="margin-top: 20px">
            @Html.HiddenFor(model => model.MAHOADON)
            @Html.HiddenFor(model => model.MASP)

            <input type="submit" class="btn btn-primary" value="Delete" />
        </p>

        <div>
            @Html.ActionLink("Back to List", "Index_Order_Details", "Home")
        </div>
    }

</body>
</html>

DOAN_CLOUND/Views/Order_Detail/Update_Order_Detail.cshtml
@model DOAN_CLOUND.Models.ORDER_DETAIL

@{
    ViewBag.Title = "Update_Order_Detail";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CreateDept</title>
    <!--Bootstrap 4-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" />
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://cdn.rawgit.com/PascaleBeier/bootstrap-validate/v2.2.0/dist/bootstrap-validate.js"></script>
</head>
<body>
    @using (Html.BeginForm("Update_Order_Detail", "Order_Detail", FormMethod.Post))
    {
        @Html.ValidationSummary(true)
        <h3 class="mt-3" style="color: blue; font-weight: bold">UPDATE ORDER</h3>

        <div class="editor-label">
            <p>Update order</p>
        </div>
        <div class="editor-field">
            @Html.DisplayFor(model => model.MAHOADON)
            @Html.ValidationMessageFor(model => model.MAHOADON)
        </div>
        <div class="editor-field">
            @Html.DisplayFor(model => model.MASP)
            @Html.ValidationMessageFor(model => model.MASP)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SOLUONG)
            @Html.ValidationMessageFor(model => model.SOLUONG)
        </div>
        <div class="editor-field">
            @Html.DisplayFor(model => model.GIA)
            @Html.ValidationMessageFor(model => model.GIA)
        </div>

        <p class="form-group" style="margin-top: 20px">
            @Html.HiddenFor(model => model.MAHOADON)
            @Html.HiddenFor(model => model.MASP)

            <input type="submit" class="btn btn-primary" value="Update" />
        </p>

        <div>
            @Html.ActionLink("Back to List", "Index_Order_Details", "Home")
        </div>
    }
</body>
</html>