DOAN_CLOUND/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DOAN_CLOUND.Models;

namespace DOAN_CLOUND.Controllers
{
    public class CartController : Controller
    {
        WebCafeDataContext db = new WebCafeDataContext();

        // GET: Cart
        public ActionResult SanPham()
        {
            var listProduct = db.PRODUCTs.ToList();
            return View(listProduct);
        }
    }
}

DOAN_CLOUND/Controllers/CategoryController.cs
using DOAN_CLOUND.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DOAN_CLOUND.Controllers
{
    public class CategoryController : Controller
    {
        // GET: Category
        public ActionResult Index()
        {
            return View();
        }

        WebCafeDataContext db = new WebCafeDataContext();   

        // Thêm category
        [HttpGet] 
        public ActionResult Create_Category()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create_Category(CATEGORy category)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var existingCategory = db.CATEGORies.FirstOrDefault(c => c.NAME ==  category.NAME);
                    if (existingCategory != null)
                    {
                        ModelState.AddModelError("", "Tên danh mục đã tồn tại. Vui lòng chọn tên khác.");
                        return View(category);
                    }
                    db.CATEGORies.InsertOnSubmit(category); // Thêm đối tượng vào bảng CATEGORIES
                    db.SubmitChanges(); // Lưu thay đổi vào cơ sở dữ liệu

                    return RedirectToAction("Index_Category", "Home");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Có lỗi xảy ra khi lưu danh mục: " + ex.Message);
                }
            }
            return View(category);
        }

        // Xóa category
        [HttpGet]
        public ActionResult Delete_Category(int id)
        {
            CATEGORy category = db.CATEGORies.Single(c => c.ID == id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        [HttpPost, ActionName("Delete_Category")]
        public ActionResult Delete_CategoryConfirmed(int id)
        {
            CATEGORy category = db.CATEGORies.Single(c => c.ID == id);
            if (category == null)
            {
                return HttpNotFound();
            }
            db.CATEGORies.DeleteOnSubmit(category);
            db.SubmitChanges();
            return RedirectToAction("Index_Category", "Home");
        }

        // Sửa category
        [HttpGet]
        public ActionResult Update_Category(int id)
        {
            CATEGORy category = db.CATEGORies.Single(c => c.ID == id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        [HttpPost]
        public ActionResult Update_Category(CATEGORy updatedCategory)
        {
            CATEGORy category = db.CATEGORies.Single(c => c.ID == updatedCategory.ID);
            if (category == null)
            {
                return HttpNotFound();
            }

            category.NAME = updatedCategory.NAME;
            db.SubmitChanges(); // Lưu lại thay đổi (này là với linQ nha)
            return RedirectToAction("Index_Category", "Home");
        }

    }
}

DOAN_CLOUND/Controllers/HomeController.cs
using DOAN_CLOUND.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using DOAN_CLOUND.Models;


namespace DOAN_CLOUND.Controllers
{
    public class HomeController : Controller
    {

        WebCafeDataContext db = new WebCafeDataContext();
        List<GioHang> listgiohang = new List<GioHang>();


        public ActionResult about()
        {
            return View();
        }
        public ActionResult blog_single()
        {
            return View();
        }

        public ActionResult blog()
        {
            return View();
        }

        public ActionResult cart()
        {
            return View();
        }

        public ActionResult checkout()
        {
            return View();
        }

        public ActionResult contact()
        {
            return View();
        }

        public ActionResult menu()
        {
            var listProduct = db.PRODUCTs.ToList();
            return View(listProduct);
        }

        public ActionResult product_single()
        {
            return View();
        }

        public ActionResult services()
        {
            return View();
        }

        public ActionResult shop()
        {
            var listProduct = db.PRODUCTs.ToList();
            return View(listProduct);
        }
        public ActionResult index()
        {
            var listProduct = db.PRODUCTs.ToList();
            return View(listProduct);
        }

        public ActionResult Index_Products()
        {
            if (Session["taikhoan"] == null)
            {
                return RedirectToAction("DangNhap", "Home");
            }
            var listProduct = db.PRODUCTs.ToList();
            return View(listProduct);
        }

        public ActionResult Index_Category()
        {
            var listCategories = db.CATEGORies.ToList();
            return View(listCategories);
        }

        public ActionResult Index_User()
        {
            var listUser = db.USERs.ToList();
            return View(listUser);
        }

        public ActionResult Index_Order()
        {
            var listOrder = db.ORDERs.ToList();
            return View(listOrder);
        }

        public ActionResult Index_Order_Details()
        {
            var listOrderDetails = db.ORDER_DETAILs.ToList();
            return View(listOrderDetails);
        }

        public ActionResult Index_Order_Details_Id(int mahd)
        {
            var listOrderDetails = db.ORDER_DETAILs.Where(x => x.MAHOADON == mahd).ToList();
            return View(listOrderDetails);
        }


        

        // đăng nhập - đăng ký
        [HttpGet]
        public ActionResult DangKy()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DangKy(USER user, FormCollection fc)
        {
            var hoten = fc["HotenKH"];

            var dienthoai = fc["Dienthoai"];
            var email = fc["Email"];
            var diachi = fc["Diachi"];

            var taikhoan = fc["TenDN"];
            var matkhau = fc["Matkhau"];

            bool kiemtra = true;

            if (string.IsNullOrEmpty(hoten))
            {
                ViewData["Loi1"] = "Ho ten khong duoc de trong";
                kiemtra = false;
            }

            if (string.IsNullOrEmpty(dienthoai))
            {
                ViewData["Loi5"] = "Dien Thoai khong duoc de trong";
                kiemtra = false;
            }


            if (string.IsNullOrEmpty(taikhoan))
            {
                ViewData["Loi2"] = "Ten dang nhap khong duoc de trong";
                kiemtra = false;
            }

            if (string.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi3"] = "Mat Khau khong duoc de trong";
                kiemtra = false;
            }

            if (kiemtra == true)
            {
                user.HOTEN = hoten;
                user.DIACHI = diachi;
                user.EMAIL = email;
                user.USERNAME = taikhoan;
                user.PASSWORD = matkhau;
                user.ROLE = "USER";
                user.SODT = dienthoai;


                //khach.DienThoai = dienthoai;
                //khach.Email = email;
                //khach.DiaChi = diachi;
                //khach.TaiKhoan = taikhoan;
                //khach.MatKhau = matkhau;


                db.USERs.InsertOnSubmit(user);
                db.SubmitChanges();
                return RedirectToAction("DangNhap", "Home");
            }

            return View();
        }

        [HttpGet]
        public ActionResult DangNhap()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DangNhap(USER user, FormCollection fc)
        {
            var taikhoan = fc["TenDN"];
            var matkhau = fc["Matkhau"];
            Session["tendn"] = fc["TenDN"];
            bool kiemtra = true;

            Session ["tendn"] = fc["TenDN"];

            if (string.IsNullOrEmpty(taikhoan))
            {
                ViewData["Loi1"] = "Ten dang nhap khong duoc de trong";
                kiemtra = false;
            }

            if (string.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi2"] = "Mat Khau khong duoc de trong";
                kiemtra = false;
            }

            if (kiemtra == true)
            {
                user.USERNAME = taikhoan;
                user.PASSWORD = matkhau;
                //db.KhachHangs.InsertOnSubmit(khach);
                //db.SubmitChanges();

                USER us = db.USERs.SingleOrDefault(c => c.USERNAME == taikhoan && c.PASSWORD == matkhau);

                if (us != null)
                {
                    if (us.ROLE == "USER")
                    {
                        ViewBag.TB = "Đăng Nhập Thành Công";
                        Session["taikhoan"] = us;
                    }
                    if (us.ROLE == "ADMIN")
                    {
                        Session["taikhoan"] = us;
                        return RedirectToAction("Index_Products", "Home");
                    }
                }
                else
                {
                    ViewBag.TB = "Đăng Nhập Thất Bại, Sai Tài Khoản Hoặc Mật Khẩu";
                    return View();
                }

                return RedirectToAction("Index", "Home");
            }

            return View();
        }
        public ActionResult DangXuat()
        {
            Session["taikhoan"] = null;
            return RedirectToAction("index", "Home");
        }

        //[HttpPost]
        //public ActionResult DangNhap(KhachHang dn)
        //{
        //    Session["loi"] = "Dang nhap khong thanh cong (sai thong tin)";
        //    Session["thongbao"] = "Dang nhap thanh cong";

        //    UsersRepository condn = new UsersRepository();
        //    string role = condn.lay_role(dn.UserName, dn.Pass);
        //    if (ModelState.IsValid)
        //    {
        //        ViewBag.kt = condn.kiemtra(dn.UserName, dn.Pass);


        //        if (ViewBag.kt == 0)
        //        {
        //            return View();
        //        }
        //        else if (role == "ADMIN")
        //        {
        //            return RedirectToAction("Index_User", "Home");
        //        }
        //        else
        //        {
        //            return RedirectToAction("index", "Home");
        //        }

        //    }

        //    return View();
        //}

        public ActionResult GioHang()
        {
            List<GioHang> listgiohang = LayGioHang();
            if (listgiohang.Count == 0)
            {
                return RedirectToAction("GioHangRong", "Home");
            }

            ViewBag.tongtien = TinhTongTien();
            ViewBag.soluong = TinhSoLuong();
            return View(listgiohang);
        }

        public ActionResult GioHangRong()
        {
            return View();
        }


        public List<GioHang> LayGioHang()
        {
            List<GioHang> listgiohang = Session["GioHang"] as List<GioHang>;
            if (listgiohang == null)
            {
                listgiohang = new List<GioHang>();
                Session["GioHang"] = listgiohang;
            }

            return listgiohang;
        }

        public ActionResult ThemGioHang(int id, string strUrl)
        {
            List<GioHang> listgiohang = LayGioHang();

            strUrl = strUrl + "#menu-scroll";

            GioHang sanphammoi = listgiohang.Find(sp => sp.Id_san_pham == id);
            if (sanphammoi == null)
            {
                sanphammoi = new GioHang(id);
                listgiohang.Add(sanphammoi);
                return Redirect(strUrl);
            }
            else
            {
                sanphammoi.Soluong++;
                return Redirect(strUrl);
            }
        }


        public float TinhTongTien()
        {
            float tongtien = 0;
            List<GioHang> listgiohang = LayGioHang();
            foreach (GioHang item in listgiohang)
            {
                tongtien += item.Thanhtien;
            }
            return tongtien;
        }

        public int TinhSoLuong()
        {
            int soluong = 0;
            List<GioHang> listgiohang = LayGioHang();
            foreach (GioHang item in listgiohang)
            {
                soluong += item.Soluong;
            }
            return soluong;
        }


        public ActionResult SoLuongGioHang()
        {
            ViewBag.soluong = TinhSoLuong();
            return View();
        }

        public ActionResult XoaGioHang(int id)
        {
            List<GioHang> listgiohang = LayGioHang();

            GioHang sanphammoi = listgiohang.Find(sp => sp.Id_san_pham == id);
            if (sanphammoi != null)
            {
                listgiohang.RemoveAll(sp => sp.Id_san_pham == id);

DOAN_CLOUND/Controllers/OrderController.cs
using DOAN_CLOUND.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DOAN_CLOUND.Controllers
{
    public class OrderController : Controller
    {
        // GET: Order
        public ActionResult Index()
        {
            return View();
        }

        WebCafeDataContext db = new WebCafeDataContext();

        // Thêm Order
        [HttpGet]
        public ActionResult Create_Order()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create_Order(ORDER order)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var existingOrder = db.ORDERs.FirstOrDefault(o => o.MAHOADON == order.MAHOADON);
                    if (existingOrder != null)
                    {
                        ModelState.AddModelError("", "Hóa đơn đã tồn tại. Vui lòng chọn hóa đơn khác.");
                        return View(order);
                    }
                    db.ORDERs.InsertOnSubmit(order); // Thêm đối tượng vào bảng ORDER
                    db.SubmitChanges(); // Lưu thay đổi vào cơ sở dữ liệu

                    return RedirectToAction("Index_Order", "Home");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Có lỗi xảy ra khi lưu hóa đơn: " + ex.Message);
                }
            }
            return View(order);
        }

        // Xóa Order
        [HttpGet]
        public ActionResult Delete_Order(int mahoadon)
        {
            ORDER order = db.ORDERs.Single(c => c.MAHOADON == mahoadon);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        [HttpPost, ActionName("Delete_Order")]
        public ActionResult Delete_OrderConfirmed(int mahoadon)
        {
            ORDER order = db.ORDERs.Single(c => c.MAHOADON == mahoadon);
            if (order == null)
            {
                return HttpNotFound();
            }
            db.ORDERs.DeleteOnSubmit(order);
            db.SubmitChanges();
            return RedirectToAction("Index_Order", "Home");
        }

        // Sửa Order
        [HttpGet]
        public ActionResult Update_Order(int mahoadon)
        {
            ORDER order = db.ORDERs.Single(c => c.MAHOADON == mahoadon);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        [HttpPost]
        public ActionResult Update_Order(ORDER updatedOrder)
        {
            ORDER order = db.ORDERs.Single(c => c.MAHOADON == updatedOrder.MAHOADON);
            if (order == null)
            {
                return HttpNotFound();
            }

            order.MAKH = updatedOrder.MAKH;
            order.NGAYLAP = updatedOrder.NGAYLAP;
            order.TONGGIA = updatedOrder.TONGGIA;
            db.SubmitChanges(); // Lưu lại thay đổi (này là với linQ nha)
            return RedirectToAction("Index_Order", "Home");
        }
    }
}

DOAN_CLOUND/Views/Home/CreateCategory.cshtml
@{
    ViewBag.Title = "CreateCategory";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

@model DOAN_CLOUND.Models.Category
<div class="card">
    <div class="card-body">
        <div class="table-responsive">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal" style="width:25%; margin:20px auto; padding:10px; box-shadow:1px 1px 2px 2px #888888; border-radius:10px">
                    <h3 style="text-align:center">Thêm mới khách hàng</h3>
                    <hr />

                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-10" })
                        <div style="max-width:100%" class="col-md-10">
                            @Html.EditorFor(model => model.Name, new { @htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-primary" />
                            <br />
                            <br />
                            <p>
                                @Html.ActionLink("Back to List", "Index_Category", "", new { @class = "btn btn-info" })
                            </p>

                        </div>
                    </div>
                </div>
            }

        </div>
    </div>
</div>

DOAN_CLOUND/Views/Home/DangKy.cshtml
@{
    ViewBag.Title = "Đăng Ký Thành Viên";
    Layout = "~/Views/Shared/_LayoutPage1_User.cshtml";
}

<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Đăng Ký Thành Viên</title>
    <!-- Bootstrap CSS -->
    <style>
        /* Cấu hình chung cho form input */
        .form-input {
            border: 1px solid black; /* Đường viền mặc định */
            border-radius: 4px; /* Độ cong góc */
            padding: 10px 15px; /* Khoảng đệm */
            font-size: 16px; /* Kích thước chữ */
            color: #495057; /* Màu chữ */
            background-color: #f8f9fa; /* Màu nền */
            transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
            max-width: 400px;
        }

            /* Khi người dùng hover vào form input */
            .form-input:hover {
                border-color: #80bdff;
                background-color: #f1f3f5;
            }

            /* Khi form input được focus */
            .form-input:focus {
                border-color: #80bdff;
                box-shadow: 0 0 5px rgba(0, 123, 255, 0.25);
                outline: none;
            }

            /* Khi form input ở trạng thái disabled */
            .form-input:disabled, .form-input[readonly] {
                background-color: #e9ecef;
                opacity: 1;
            }

        /* Select dropdown */
        .form-input-select {
            background-color: #fff;
            border: 1px solid #ced4da;
            color: #495057;
            padding: 8px 15px;
            border-radius: 4px;
            -webkit-appearance: none;
            -moz-appearance: none;
            appearance: none;
        }

            .form-input-select:focus {
                border-color: #80bdff;
                box-shadow: 0 0 5px rgba(0, 123, 255, 0.25);
            }

        /* Table cell configuration */
        .table tbody tr td {
            padding: 0;
            max-width: 400px;
            color: white;
        }

        /* Căn giữa form trong màn hình */
        form {
            width: 800px;
            margin: 0 auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        }

        /* Căn chỉnh các trường nhập liệu */
        .form-input {
            width: 100%;
            margin-bottom: 15px;
            box-sizing: border-box;
        }

        /* Định dạng nút Đăng ký */
        button[type="submit"] {
            background-color: #a67c52;
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            width: 100%;
        }

            button[type="submit"]:hover {
                background-color: #8c5f35;
            }

            td {
                max-width: 400px;
                color: white;
                text-align: center;
            }

            table {
                width: 600px;
            }


    </style>
</head>
<body>

    <div class="container-fluid mt-5">
        <h2 class="text-center mb-4">ĐĂNG KÝ THÀNH VIÊN</h2>
        <div class="row justify-content-center">
            <div class="col-md-8 p-3" style=" display:flex; justify-content:center;">
                <table>
                    @using (Html.BeginForm())
                    {
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <tr>
                            <td class="text-end fw-bold">Họ Tên KH:</td>
                            <td>@Html.TextBox("HotenKH", "", new { @class = "form-input" }) @ViewData["Loi1"]</td>
                        </tr>
                        <tr>
                            <td class="text-end fw-bold">Tên Đăng nhập:</td>
                            <td>@Html.TextBox("TenDN", "", new { @class = "form-input" }) @ViewData["Loi2"]</td>
                        </tr>
                        <tr>
                            <td class="text-end fw-bold">Mật Khẩu:</td>
                            <td>@Html.Password("Matkhau", "", new { @class = "form-input" }) @ViewData["Loi3"]</td>
                        </tr>
                        <tr>
                            <td class="text-end fw-bold">Nhập lại Mật khẩu:</td>
                            <td>@Html.Password("ReMatkhau", "", new { @class = "form-input" }) @ViewData["Loi4"]</td>
                        </tr>
                        <tr>
                            <td class="text-end fw-bold">Điện thoại:</td>
                            <td>@Html.TextBox("Dienthoai", "", new { @class = "form-input" }) @ViewData["Loi5"]</td>
                        </tr>
                        <tr>
                            <td class="text-end fw-bold">Ngày sinh:</td>
                            <td><input type="date" name="NgaySinh" class="form-input" /></td>
                        </tr>
                        <tr>
                            <td class="text-end fw-bold">Email:</td>
                            <td><input type="text" name="Email" class="form-input" /></td>
                        </tr>
                        <tr>
                            <td class="text-end fw-bold">Địa Chỉ:</td>
                            <td><input type="text" name="Diachi" class="form-input" /></td>
                        </tr>
                        <tr>
                            <td class="text-center" colspan="2">
                                <button type="submit" class="btn btn-primary btn-sm">ĐĂNG KÝ</button>
                            </td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>
</body>
</html>

DOAN_CLOUND/Views/Home/Details_Caterory.cshtml
@{
    ViewBag.Title = "Details_Caterory";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}
@model DOAN_CLOUND.Models.Category
<div class="card">
    <div class="card-body">
        <div class="table-responsive">
            <div class="form-horizontal" style="width:25%; margin:20px auto; padding:10px; box-shadow:1px 1px 2px 2px #888888; border-radius:10px">
                <h4>Thông Tin Loại Hàng </h4>
                <hr />
                <dl class="dl-horizontal">
                    <dt>ID</dt>
                    <dd>@Model.Id</dd>

                    <dt>Tên loại</dt>
                    <dd>@Model.Name</dd>
                    <p>
                        @Html.ActionLink("Back to List", "Index_Category", "", new { @class = "btn btn-info" })
                    </p>
                </dl>
            </div>

        </div>
    </div>
</div>

DOAN_CLOUND/Views/Home/EditCategory.cshtml
@{
    ViewBag.Title = "EditCategory";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

@model DOAN_CLOUND.Models.Category
<div class="card">
    <div class="card-body">
        <div class="table-responsive">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal" style="width:25%; margin:20px auto; padding:10px; box-shadow:1px 1px 2px 2px #888888; border-radius:10px">
                    <h4 style="text-align:center">Chỉnh Sửa Khách Hàng</h4>
                    <hr />
                    @Html.HiddenFor(model => model.Id)
                    <div class="form-group">
                        @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-10" })
                        <div style="max-width:100%" class="col-md-10">
                            @Html.EditorFor(model => model.Id, new { @htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-10" })
                        <div style="max-width:100%" class="col-md-10">
                            @Html.EditorFor(model => model.Name, new { @htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>
      

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-primary" />
                            <br />
                            <br />
                            <p>
                                @Html.ActionLink("Back to List", "Index_Category", "", new { @class = "btn btn-info" })
                            </p>
                        </div>

                    </div>
                </div>
            }

        </div>
    </div>
</div>

DOAN_CLOUND/Views/Home/GioHangRong.cshtml
@{
    ViewBag.Title = "menu";
    Layout = "~/Views/Shared/_LayoutPage1_User.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>GioHangRong</title>
    <style>
        h1 {
            font-size: 70px;
        }

        a{
            font-size: 30px;
        }
    </style>
</head>
<body>
    <div class="">
        <h1 class="text-danger text-center mt-3">Giỏ Hàng Rỗng</h1>
        <h2 class="text-white text-center">Xin Vui Lòng Order Món Giúp Chúng Tớ Nhé!!!</h2>
        <p class="text-center"><a class="text-center text-warning" href="@Url.Action("menu", "Home")">Go to Menu</a></p>
    </div>
</body>
</html>

DOAN_CLOUND/Views/Home/Index_Category.cshtml
@model IEnumerable<DOAN_CLOUND.Models.CATEGORy>

@{
    ViewBag.Title = "Index_Category";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<h2>Category</h2>

<p>
    @Html.ActionLink("Create New", "Create_Category", "Category") 
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NAME)
        </th>
        <th>FEATURE</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NAME)
        </td>
        <td>
            @Html.ActionLink("Update", "Update_Category", "Category", new { id = item.ID }, null) |
            @Html.ActionLink("Delete", "Delete_Category", "Category", new { id = item.ID }, null)
        </td>
    </tr>
}

</table>

DOAN_CLOUND/Views/Home/Index_Order.cshtml
@model IEnumerable<DOAN_CLOUND.Models.ORDER>

@{
    ViewBag.Title = "Index_Order";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<h2>Index_Order</h2>

<p>
    @Html.ActionLink("Create New", "Create_Order", "Order")
</p>    
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MAHOADON)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MAKH)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NGAYLAP)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TONGGIA)
        </th>
        <th>TINHNANG</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.MAHOADON)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MAKH)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NGAYLAP)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TONGGIA)
        </td>
        <td>
            @Html.ActionLink("Update", "Update_Order", "Order", new { mahoadon = item.MAHOADON }, null) |
            @Html.ActionLink("Details", "Index_Order_Details_Id", "Home", new { mahd = item.MAHOADON }, null) |
            @Html.ActionLink("Delete", "Delete_Order", "Order", new { mahoadon = item.MAHOADON }, null)
        </td>
    </tr>
}

</table>